#!/bin/bash
PAYLOADS=${1}
OPTIONS="-DAPP=groundstation
-DSCH_OS=LINUX
-DSCH_GND_ADD_PAYLOADS=${PAYLOADS}
-DSCH_GND_ADD_GS=0
-DSCH_ARCH=X86
-DSCH_NAME=\"GROUNDSTATION\"
-DSCH_ST_MODE=SQLITE
-DSCH_COMM_NODE=10
-DSCH_DEVICE_ID=10
-DSCH_HOOK_COMM=1
-DSCH_CSP_BUFFERS=1000
-DSCH_COM_TX_DELAY_MS=100
-DSCH_MAX_WDT_TIMER=9999999
-DSCH_MAX_GND_WDT_TIMER=9999999
-DSCH_STORAGE_FILE=\"suchai\"
-DSCH_CSP_CONN_TIMEOUT=250
-DSCH_CSP_READ_TIMEOUT=50
-DSCH_LOG_ENABLE_MONGODB=1
-DSCH_LOG_MONGODB_HOST=\"localhost\"
-DSCH_LOG_MONGODB_PORT=27017
-DSCH_LOG_MONGODB_NAME=\"suchai-log\""

rm -rf build-gnd
cmake -B build-gnd -G Ninja $OPTIONS && cmake --build build-gnd -j4
exit $?
